// Font Awesome icon names (without 'fa fa-' prefix)
export const fontAwesomeIcons = [
  "adjust",
  "adn",
  "align-center",
  "align-justify",
  "align-left",
  "align-right",
  "ambulance",
  "anchor",
  "android",
  "angellist",
  "angle-double-down",
  "angle-double-left",
  "angle-double-right",
  "angle-double-up",
  "angle-down",
  "angle-left",
  "angle-right",
  "angle-up",
  "apple",
  "archive",
  "area-chart",
  "arrow-circle-down",
  "arrow-circle-left",
  "arrow-circle-o-down",
  "arrow-circle-o-left",
  "arrow-circle-o-right",
  "arrow-circle-o-up",
  "arrow-circle-right",
  "arrow-circle-up",
  "arrow-down",
  "arrow-left",
  "arrow-right",
  "arrow-up",
  "arrows",
  "arrows-alt",
  "arrows-h",
  "arrows-v",
  "asterisk",
  "at",
  "automobile",
  "backward",
  "balance-scale",
  "ban",
  "bank",
  "bar-chart",
  "bar-chart-o",
  "barcode",
  "bars",
  "battery-0",
  "battery-1",
  "battery-2",
  "battery-3",
  "battery-4",
  "battery-empty",
  "battery-full",
  "battery-half",
  "battery-quarter",
  "battery-three-quarters",
  "bed",
  "beer",
  "behance",
  "behance-square",
  "bell",
  "bell-o",
  "bell-slash",
  "bell-slash-o",
  "bicycle",
  "binoculars",
  "birthday-cake",
  "bitbucket",
  "bitbucket-square",
  "bitcoin",
  "black-tie",
  "bold",
  "bolt",
  "bomb",
  "book",
  "bookmark",
  "bookmark-o",
  "briefcase",
  "btc",
  "bug",
  "building",
  "building-o",
  "bullhorn",
  "bullseye",
  "bus",
  "buysellads",
  "cab",
  "calculator",
  "calendar",
  "calendar-check-o",
  "calendar-minus-o",
  "calendar-o",
  "calendar-plus-o",
  "calendar-times-o",
  "camera",
  "camera-retro",
  "car",
  "caret-down",
  "caret-left",
  "caret-right",
  "caret-square-o-down",
  "caret-square-o-left",
  "caret-square-o-right",
  "caret-square-o-up",
  "caret-up",
  "cart-arrow-down",
  "cart-plus",
  "cc",
  "cc-amex",
  "cc-diners-club",
  "cc-discover",
  "cc-jcb",
  "cc-mastercard",
  "cc-paypal",
  "cc-stripe",
  "cc-visa",
  "certificate",
  "chain",
  "chain-broken",
  "check",
  "check-circle",
  "check-circle-o",
  "check-square",
  "check-square-o",
  "chevron-circle-down",
  "chevron-circle-left",
  "chevron-circle-right",
  "chevron-circle-up",
  "chevron-down",
  "chevron-left",
  "chevron-right",
  "chevron-up",
  "child",
  "chrome",
  "circle",
  "circle-o",
  "circle-o-notch",
  "circle-thin",
  "clipboard",
  "clock-o",
  "clone",
  "close",
  "cloud",
  "cloud-download",
  "cloud-upload",
  "cny",
  "code",
  "code-fork",
  "codepen",
  "coffee",
  "cog",
  "cogs",
  "columns",
  "comment",
  "comment-o",
  "commenting",
  "commenting-o",
  "comments",
  "comments-o",
  "compass",
  "compress",
  "connectdevelop",
  "contao",
  "copy",
  "copyright",
  "creative-commons",
  "credit-card",
  "crop",
  "crosshairs",
  "css3",
  "cube",
  "cubes",
  "cut",
  "cutlery",
  "dashboard",
  "dashcube",
  "database",
  "dedent",
  "delicious",
  "desktop",
  "deviantart",
  "diamond",
  "digg",
  "dollar",
  "dot-circle-o",
  "download",
  "dribbble",
  "dropbox",
  "drupal",
  "edit",
  "eject",
  "ellipsis-h",
  "ellipsis-v",
  "empire",
  "envelope",
  "envelope-o",
  "envelope-square",
  "eraser",
  "eur",
  "euro",
  "exchange",
  "exclamation",
  "exclamation-circle",
  "exclamation-triangle",
  "expand",
  "expeditedssl",
  "external-link",
  "external-link-square",
  "eye",
  "eye-slash",
  "eyedropper",
  "facebook",
  "facebook-f",
  "facebook-official",
  "facebook-square",
  "fast-backward",
  "fast-forward",
  "fax",
  "feed",
  "female",
  "fighter-jet",
  "file",
  "file-archive-o",
  "file-audio-o",
  "file-code-o",
  "file-excel-o",
  "file-image-o",
  "file-movie-o",
  "file-o",
  "file-pdf-o",
  "file-photo-o",
  "file-picture-o",
  "file-powerpoint-o",
  "file-sound-o",
  "file-text",
  "file-text-o",
  "file-video-o",
  "file-word-o",
  "file-zip-o",
  "files-o",
  "film",
  "filter",
  "fire",
  "fire-extinguisher",
  "firefox",
  "flag",
  "flag-checkered",
  "flag-o",
  "flash",
  "flask",
  "flickr",
  "floppy-o",
  "folder",
  "folder-o",
  "folder-open",
  "folder-open-o",
  "font",
  "fonticons",
  "forumbee",
  "forward",
  "foursquare",
  "frown-o",
  "futbol-o",
  "gamepad",
  "gavel",
  "gbp",
  "ge",
  "gear",
  "gears",
  "genderless",
  "get-pocket",
  "gg",
  "gg-circle",
  "gift",
  "git",
  "git-square",
  "github",
  "github-alt",
  "github-square",
  "gittip",
  "glass",
  "globe",
  "google",
  "google-plus",
  "google-plus-square",
  "google-wallet",
  "graduation-cap",
  "gratipay",
  "group",
  "h-square",
  "hacker-news",
  "hand-grab-o",
  "hand-lizard-o",
  "hand-o-down",
  "hand-o-left",
  "hand-o-right",
  "hand-o-up",
  "hand-paper-o",
  "hand-peace-o",
  "hand-pointer-o",
  "hand-rock-o",
  "hand-scissors-o",
  "hand-spock-o",
  "hand-stop-o",
  "hdd-o",
  "header",
  "headphones",
  "heart",
  "heart-o",
  "heartbeat",
  "history",
  "home",
  "hospital-o",
  "hotel",
  "hourglass",
  "hourglass-1",
  "hourglass-2",
  "hourglass-3",
  "hourglass-end",
  "hourglass-half",
  "hourglass-o",
  "hourglass-start",
  "houzz",
  "html5",
  "i-cursor",
  "ils",
  "image",
  "inbox",
  "indent",
  "industry",
  "info",
  "info-circle",
  "inr",
  "instagram",
  "institution",
  "internet-explorer",
  "intersex",
  "ioxhost",
  "italic",
  "joomla",
  "jpy",
  "jsfiddle",
  "key",
  "keyboard-o",
  "krw",
  "language",
  "laptop",
  "lastfm",
  "lastfm-square",
  "leaf",
  "leanpub",
  "legal",
  "lemon-o",
  "level-down",
  "level-up",
  "life-bouy",
  "life-buoy",
  "life-ring",
  "life-saver",
  "lightbulb-o",
  "line-chart",
  "link",
  "linkedin",
  "linkedin-square",
  "linux",
  "list",
  "list-alt",
  "list-ol",
  "list-ul",
  "location-arrow",
  "lock",
  "long-arrow-down",
  "long-arrow-left",
  "long-arrow-right",
  "long-arrow-up",
  "magic",
  "magnet",
  "mail-forward",
  "mail-reply",
  "mail-reply-all",
  "male",
  "map",
  "map-marker",
  "map-o",
  "map-pin",
  "map-signs",
  "mars",
  "mars-double",
  "mars-stroke",
  "mars-stroke-h",
  "mars-stroke-v",
  "maxcdn",
  "meanpath",
  "medium",
  "medkit",
  "meh-o",
  "mercury",
  "microphone",
  "microphone-slash",
  "minus",
  "minus-circle",
  "minus-square",
  "minus-square-o",
  "mobile",
  "mobile-phone",
  "money",
  "moon-o",
  "mortar-board",
  "motorcycle",
  "mouse-pointer",
  "music",
  "navicon",
  "neuter",
  "newspaper-o",
  "object-group",
  "object-ungroup",
  "odnoklassniki",
  "odnoklassniki-square",
  "opencart",
  "openid",
  "opera",
  "optin-monster",
  "outdent",
  "pagelines",
  "paint-brush",
  "paper-plane",
  "paper-plane-o",
  "paperclip",
  "paragraph",
  "paste",
  "pause",
  "paw",
  "paypal",
  "pencil",
  "pencil-square",
  "pencil-square-o",
  "phone",
  "phone-square",
  "photo",
  "picture-o",
  "pie-chart",
  "pied-piper",
  "pied-piper-alt",
  "pinterest",
  "pinterest-p",
  "pinterest-square",
  "plane",
  "play",
  "play-circle",
  "play-circle-o",
  "plug",
  "plus",
  "plus-circle",
  "plus-square",
  "plus-square-o",
  "power-off",
  "print",
  "puzzle-piece",
  "qq",
  "qrcode",
  "question",
  "question-circle",
  "quote-left",
  "quote-right",
  "ra",
  "random",
  "rebel",
  "recycle",
  "reddit",
  "reddit-square",
  "refresh",
  "registered",
  "remove",
  "renren",
  "reorder",
  "repeat",
  "reply",
  "reply-all",
  "retweet",
  "rmb",
  "road",
  "rocket",
  "rotate-left",
  "rotate-right",
  "rouble",
  "rss",
  "rss-square",
  "rub",
  "ruble",
  "rupee",
  "safari",
  "save",
  "scissors",
  "search",
  "search-minus",
  "search-plus",
  "sellsy",
  "send",
  "send-o",
  "server",
  "share",
  "share-alt",
  "share-alt-square",
  "share-square",
  "share-square-o",
  "shekel",
  "sheqel",
  "shield",
  "ship",
  "shirtsinbulk",
  "shopping-cart",
  "sign-in",
  "sign-out",
  "signal",
  "simplybuilt",
  "sitemap",
  "skyatlas",
  "skype",
  "slack",
  "sliders",
  "slideshare",
  "smile-o",
  "soccer-ball-o",
  "sort",
  "sort-alpha-asc",
  "sort-alpha-desc",
  "sort-amount-asc",
  "sort-amount-desc",
  "sort-asc",
  "sort-desc",
  "sort-down",
  "sort-numeric-asc",
  "sort-numeric-desc",
  "sort-up",
  "soundcloud",
  "space-shuttle",
  "spinner",
  "spoon",
  "spotify",
  "square",
  "square-o",
  "stack-exchange",
  "stack-overflow",
  "star",
  "star-half",
  "star-half-empty",
  "star-half-full",
  "star-half-o",
  "star-o",
  "steam",
  "steam-square",
  "step-backward",
  "step-forward",
  "stethoscope",
  "sticky-note",
  "sticky-note-o",
  "stop",
  "street-view",
  "strikethrough",
  "stumbleupon",
  "stumbleupon-circle",
  "subscript",
  "subway",
  "suitcase",
  "sun-o",
  "superscript",
  "support",
  "table",
  "tablet",
  "tachometer",
  "tag",
  "tags",
  "tasks",
  "taxi",
  "television",
  "tencent-weibo",
  "terminal",
  "text-height",
  "text-width",
  "th",
  "th-large",
  "th-list",
  "thumb-tack",
  "thumbs-down",
  "thumbs-o-down",
  "thumbs-o-up",
  "thumbs-up",
  "ticket",
  "times",
  "times-circle",
  "times-circle-o",
  "tint",
  "toggle-down",
  "toggle-left",
  "toggle-off",
  "toggle-on",
  "toggle-right",
  "toggle-up",
  "trademark",
  "train",
  "transgender",
  "transgender-alt",
  "trash",
  "trash-o",
  "tree",
  "trello",
  "tripadvisor",
  "trophy",
  "truck",
  "try",
  "tty",
  "tumblr",
  "tumblr-square",
  "turkish-lira",
  "tv",
  "twitch",
  "twitter",
  "twitter-square",
  "umbrella",
  "underline",
  "undo",
  "university",
  "unlink",
  "unlock",
  "unlock-alt",
  "unsorted",
  "upload",
  "usd",
  "user",
  "user-md",
  "user-plus",
  "user-secret",
  "user-times",
  "users",
  "venus",
  "venus-double",
  "venus-mars",
  "viacoin",
  "video-camera",
  "vimeo",
  "vimeo-square",
  "vine",
  "vk",
  "volume-down",
  "volume-off",
  "volume-up",
  "warning",
  "wechat",
  "weibo",
  "weixin",
  "whatsapp",
  "wheelchair",
  "wifi",
  "wikipedia-w",
  "windows",
  "won",
  "wordpress",
  "wrench",
  "xing",
  "xing-square",
  "y-combinator",
  "y-combinator-square",
  "yahoo",
  "yc",
  "yc-square",
  "yelp",
  "yen",
  "youtube",
  "youtube-play",
  "youtube-square"
];

// Animation names
export const animationNames = [
  "bounce",
  "flash",
  "pulse",
  "rubberBand",
  "shake",
  "headShake",
  "swing",
  "tada",
  "wobble",
  "jello",
  "bounceIn",
  "bounceInDown",
  "bounceInLeft",
  "bounceInRight",
  "bounceInUp",
  "bounceOut",
  "bounceOutDown",
  "bounceOutLeft",
  "bounceOutRight",
  "bounceOutUp",
  "fadeIn",
  "fadeInDown",
  "fadeInDownBig",
  "fadeInLeft",
  "fadeInLeftBig",
  "fadeInRight",
  "fadeInRightBig",
  "fadeInUp",
  "fadeInUpBig",
  "fadeOut",
  "fadeOutDown",
  "fadeOutDownBig",
  "fadeOutLeft",
  "fadeOutLeftBig",
  "fadeOutRight",
  "fadeOutRightBig",
  "fadeOutUp",
  "fadeOutUpBig",
  "flipInX",
  "flipInY",
  "flipOutX",
  "flipOutY",
  "lightSpeedIn",
  "lightSpeedOut",
  "rotateIn",
  "rotateInDownLeft",
  "rotateInDownRight",
  "rotateInUpLeft",
  "rotateInUpRight",
  "rotateOut",
  "rotateOutDownLeft",
  "rotateOutDownRight",
  "rotateOutUpLeft",
  "rotateOutUpRight",
  "hinge",
  "jackInTheBox",
  "rollIn",
  "rollOut",
  "zoomIn",
  "zoomInDown",
  "zoomInLeft",
  "zoomInRight",
  "zoomInUp",
  "zoomOut",
  "zoomOutDown",
  "zoomOutLeft",
  "zoomOutRight",
  "zoomOutUp",
  "slideInDown",
  "slideInLeft",
  "slideInRight",
  "slideInUp",
  "slideOutDown",
  "slideOutLeft",
  "slideOutRight",
  "slideOutUp"
];



// // Wavicon glyphMap - Common WaveMaker icons
// export const waviconGlyphMap: Record<string, string> = {
//   "3d-rotation": "\ue84d",
//   "ac-unit": "\ueb3b",
//   "access-alarm": "\ue190",
//   "access-alarms": "\ue191",
//   "access-time": "\ue192",
//   "accessibility": "\ue84e",
//   "account-balance": "\ue84f",
//   "account-balance-wallet": "\ue850",
//   "account-box": "\ue851",
//   "account-circle": "\ue853",
//   "add": "\ue145",
//   "add-a-photo": "\ue439",
//   "add-alarm": "\ue193",
//   "add-alert": "\ue003",
//   "add-box": "\ue146",
//   "add-circle": "\ue147",
//   "add-circle-outline": "\ue148",
//   "add-shopping-cart": "\ue854",
//   "alarm": "\ue855",
//   "alarm-add": "\ue856",
//   "alarm-off": "\ue857",
//   "alarm-on": "\ue858",
//   "album": "\ue019",
//   "android": "\ue859",
//   "announcement": "\ue85a",
//   "apps": "\ue5c3",
//   "archive": "\ue149",
//   "arrow-back": "\ue5c4",
//   "arrow-downward": "\ue5db",
//   "arrow-drop-down": "\ue5c5",
//   "arrow-drop-up": "\ue5c7",
//   "arrow-forward": "\ue5c8",
//   "arrow-upward": "\ue5d8",
//   "attach-file": "\ue226",
//   "attach-money": "\ue227",
//   "attachment": "\ue2bc",
//   "audiotrack": "\ue3a1",
//   "autorenew": "\ue863",
//   "backup": "\ue864",
//   "battery-alert": "\ue19c",
//   "battery-charging-full": "\ue1a3",
//   "battery-full": "\ue1a4",
//   "battery-std": "\ue1a5",
//   "battery-unknown": "\ue1a6",
//   "bell": "\ue7f4",
//   "block": "\ue14b",
//   "bluetooth": "\ue1a7",
//   "bluetooth-audio": "\ue60f",
//   "bluetooth-connected": "\ue1a8",
//   "bluetooth-disabled": "\ue1a9",
//   "bluetooth-searching": "\ue1aa",
//   "book": "\ue865",
//   "bookmark": "\ue866",
//   "bookmark-border": "\ue867",
//   "brightness-1": "\ue3a2",
//   "brightness-2": "\ue3a3",
//   "brightness-3": "\ue3a4",
//   "brightness-4": "\ue3a5",
//   "brightness-5": "\ue3a6",
//   "brightness-6": "\ue3a7",
//   "brightness-7": "\ue3a8",
//   "bug-report": "\ue868",
//   "build": "\ue869",
//   "business": "\ue0af",
//   "cached": "\ue86a",
//   "cake": "\ue7e9",
//   "calendar": "\ue8df",
//   "call": "\ue0b0",
//   "call-end": "\ue0b1",
//   "call-made": "\ue0b2",
//   "call-merge": "\ue0b3",
//   "call-missed": "\ue0b4",
//   "call-received": "\ue0b5",
//   "call-split": "\ue0b6",
//   "camera": "\ue3af",
//   "camera-alt": "\ue3b0",
//   "camera-enhance": "\ue8fc",
//   "camera-front": "\ue3b1",
//   "camera-rear": "\ue3b2",
//   "camera-roll": "\ue3b3",
//   "cancel": "\ue5c9",
//   "card-giftcard": "\ue8f6",
//   "card-membership": "\ue8f7",
//   "card-travel": "\ue8f8",
//   "cast": "\ue307",
//   "cast-connected": "\ue308",
//   "center-focus-strong": "\ue3b4",
//   "center-focus-weak": "\ue3b5",
//   "change-history": "\ue86b",
//   "chat": "\ue0b7",
//   "chat-bubble": "\ue0ca",
//   "chat-bubble-outline": "\ue0cb",
//   "check": "\ue5ca",
//   "check-box": "\ue834",
//   "check-box-outline-blank": "\ue835",
//   "check-circle": "\ue86c",
//   "chevron-left": "\ue5cb",
//   "chevron-right": "\ue5cc",
//   "child-care": "\ueb41",
//   "child-friendly": "\ueb42",
//   "chrome-reader-mode": "\ue86d",
//   "class": "\ue86e",
//   "clear": "\ue14c",
//   "clear-all": "\ue0b8",
//   "close": "\ue5cd",
//   "closed-caption": "\ue01c",
//   "cloud": "\ue2bd",
//   "cloud-circle": "\ue2be",
//   "cloud-done": "\ue2bf",
//   "cloud-download": "\ue2c0",
//   "cloud-off": "\ue2c1",
//   "cloud-queue": "\ue2c2",
//   "cloud-upload": "\ue2c3",
//   "code": "\ue86f",
//   "collections": "\ue3b6",
//   "collections-bookmark": "\ue431",
//   "color-lens": "\ue3b7",
//   "comment": "\ue0b9",
//   "compare": "\ue3b8",
//   "compare-arrows": "\ue915",
//   "computer": "\ue30a",
//   "confirmation-number": "\ue638",
//   "contact-mail": "\ue0d0",
//   "contact-phone": "\ue0cf",
//   "contacts": "\ue0ba",
//   "content-copy": "\ue14d",
//   "content-cut": "\ue14e",
//   "content-paste": "\ue14f",
//   "control-point": "\ue3ba",
//   "control-point-duplicate": "\ue3bb",
//   "copyright": "\ue90c",
//   "create": "\ue150",
//   "create-new-folder": "\ue2cc",
//   "credit-card": "\ue870",
//   "crop": "\ue3be",
//   "crop-16-9": "\ue3bc",
//   "crop-3-2": "\ue3bd",
//   "crop-5-4": "\ue3bf",
//   "crop-7-5": "\ue3c0",
//   "crop-din": "\ue3c1",
//   "crop-free": "\ue3c2",
//   "crop-landscape": "\ue3c3",
//   "crop-original": "\ue3c4",
//   "crop-portrait": "\ue3c5",
//   "crop-rotate": "\ue437",
//   "crop-square": "\ue3c6",
//   "dashboard": "\ue871",
//   "data-usage": "\ue1af",
//   "date-range": "\ue916",
//   "dehaze": "\ue3c7",
//   "delete": "\ue872",
//   "delete-forever": "\ue92b",
//   "delete-sweep": "\ue16c",
//   "description": "\ue873",
//   "desktop-mac": "\ue30b",
//   "desktop-windows": "\ue30c",
//   "details": "\ue3c8",
//   "developer-board": "\ue30d",
//   "developer-mode": "\ue1b0",
//   "device-hub": "\ue335",
//   "devices": "\ue1b1",
//   "devices-other": "\ue337",
//   "dialer-sip": "\ue0bb",
//   "dialpad": "\ue0bc",
//   "directions": "\ue52e",
//   "directions-bike": "\ue52f",
//   "directions-boat": "\ue532",
//   "directions-bus": "\ue530",
//   "directions-car": "\ue531",
//   "directions-railway": "\ue534",
//   "directions-run": "\ue566",
//   "directions-subway": "\ue533",
//   "directions-transit": "\ue535",
//   "directions-walk": "\ue536",
//   "disc-full": "\ue610",
//   "dns": "\ue875",
//   "do-not-disturb": "\ue612",
//   "do-not-disturb-alt": "\ue611",
//   "do-not-disturb-off": "\ue643",
//   "do-not-disturb-on": "\ue644",
//   "dock": "\ue30e",
//   "domain": "\ue7ee",
//   "done": "\ue876",
//   "done-all": "\ue877",
//   "donut-large": "\ue917",
//   "donut-small": "\ue918",
//   "drafts": "\ue151",
//   "drag-handle": "\ue25d",
//   "drive-eta": "\ue613",
//   "dvr": "\ue1b2",
//   "edit": "\ue3c9",
//   "edit-location": "\ue568",
//   "eject": "\ue8fb",
//   "email": "\ue0be",
//   "enhanced-encryption": "\ue63f",
//   "equalizer": "\ue01d",
//   "error": "\ue000",
//   "error-outline": "\ue001",
//   "euro-symbol": "\ue926",
//   "ev-station": "\ue56d",
//   "event": "\ue878",
//   "event-available": "\ue614",
//   "event-busy": "\ue615",
//   "event-note": "\ue616",
//   "event-seat": "\ue903",
//   "exit-to-app": "\ue879",
//   "expand-less": "\ue5ce",
//   "expand-more": "\ue5cf",
//   "explicit": "\ue01e",
//   "explore": "\ue87a",
//   "exposure": "\ue3ca",
//   "exposure-neg-1": "\ue3cb",
//   "exposure-neg-2": "\ue3cc",
//   "exposure-plus-1": "\ue3cd",
//   "exposure-plus-2": "\ue3ce",
//   "exposure-zero": "\ue3cf",
//   "extension": "\ue87b",
//   "face": "\ue87c",
//   "fast-forward": "\ue01f",
//   "fast-rewind": "\ue020",
//   "favorite": "\ue87d",
//   "favorite-border": "\ue87e",
//   "featured-play-list": "\ue06d",
//   "featured-video": "\ue06e",
//   "feedback": "\ue87f",
//   "fiber-dvr": "\ue05d",
//   "fiber-manual-record": "\ue061",
//   "fiber-new": "\ue05e",
//   "fiber-pin": "\ue06a",
//   "fiber-smart-record": "\ue062",
//   "file-download": "\ue2c4",
//   "file-upload": "\ue2c6",
//   "filter": "\ue3d3",
//   "filter-1": "\ue3d0",
//   "filter-2": "\ue3d1",
//   "filter-3": "\ue3d2",
//   "filter-4": "\ue3d4",
//   "filter-5": "\ue3d5",
//   "filter-6": "\ue3d6",
//   "filter-7": "\ue3d7",
//   "filter-8": "\ue3d8",
//   "filter-9": "\ue3d9",
//   "filter-9-plus": "\ue3da",
//   "filter-b-and-w": "\ue3db",
//   "filter-center-focus": "\ue3dc",
//   "filter-drama": "\ue3dd",
//   "filter-frames": "\ue3de",
//   "filter-hdr": "\ue3df",
//   "filter-list": "\ue152",
//   "filter-none": "\ue3e0",
//   "filter-tilt-shift": "\ue3e2",
//   "filter-vintage": "\ue3e3",
//   "find-in-page": "\ue880",
//   "find-replace": "\ue881",
//   "fingerprint": "\ue90d",
//   "first-page": "\ue5dc",
//   "fitness-center": "\ueb43",
//   "flag": "\ue153",
//   "flare": "\ue3e4",
//   "flash-auto": "\ue3e5",
//   "flash-off": "\ue3e6",
//   "flash-on": "\ue3e7",
//   "flight": "\ue539",
//   "flight-land": "\ue904",
//   "flight-takeoff": "\ue905",
//   "flip": "\ue3e8",
//   "flip-to-back": "\ue882",
//   "flip-to-front": "\ue883",
//   "folder": "\ue2c7",
//   "folder-open": "\ue2c8",
//   "folder-shared": "\ue2c9",
//   "folder-special": "\ue617",
//   "font-download": "\ue167",
//   "format-align-center": "\ue234",
//   "format-align-justify": "\ue235",
//   "format-align-left": "\ue236",
//   "format-align-right": "\ue237",
//   "format-bold": "\ue238",
//   "format-clear": "\ue239",
//   "format-color-fill": "\ue23a",
//   "format-color-reset": "\ue23b",
//   "format-color-text": "\ue23c",
//   "format-indent-decrease": "\ue23d",
//   "format-indent-increase": "\ue23e",
//   "format-italic": "\ue23f",
//   "format-line-spacing": "\ue240",
//   "format-list-bulleted": "\ue241",
//   "format-list-numbered": "\ue242",
//   "format-paint": "\ue243",
//   "format-quote": "\ue244",
//   "format-shapes": "\ue25e",
//   "format-size": "\ue245",
//   "format-strikethrough": "\ue246",
//   "format-textdirection-l-to-r": "\ue247",
//   "format-textdirection-r-to-l": "\ue248",
//   "format-underlined": "\ue249",
//   "forum": "\ue0bf",
//   "forward": "\ue154",
//   "forward-10": "\ue056",
//   "forward-30": "\ue057",
//   "forward-5": "\ue058",
//   "free-breakfast": "\ueb44",
//   "fullscreen": "\ue5d0",
//   "fullscreen-exit": "\ue5d1",
//   "functions": "\ue24a",
//   "g-translate": "\ue927",
//   "gamepad": "\ue30f",
//   "games": "\ue021",
//   "gavel": "\ue90e",
//   "gesture": "\ue155",
//   "get-app": "\ue884",
//   "gif": "\ue908",
//   "golf-course": "\ueb45",
//   "gps-fixed": "\ue1b3",
//   "gps-not-fixed": "\ue1b4",
//   "gps-off": "\ue1b5",
//   "grade": "\ue885",
//   "gradient": "\ue3e9",
//   "grain": "\ue3ea",
//   "graphic-eq": "\ue1b8",
//   "grid-off": "\ue3eb",
//   "grid-on": "\ue3ec",
//   "group": "\ue7ef",
//   "group-add": "\ue7f0",
//   "group-work": "\ue886",
//   "hd": "\ue052",
//   "hdr-off": "\ue3ed",
//   "hdr-on": "\ue3ee",
//   "hdr-strong": "\ue3f1",
//   "hdr-weak": "\ue3f2",
//   "headset": "\ue310",
//   "headset-mic": "\ue311",
//   "healing": "\ue3f3",
//   "hearing": "\ue023",
//   "help": "\ue887",
//   "help-outline": "\ue8fd",
//   "high-quality": "\ue024",
//   "highlight": "\ue25f",
//   "highlight-off": "\ue888",
//   "history": "\ue889",
//   "home": "\ue88a",
//   "hot-tub": "\ueb46",
//   "hotel": "\ue53a",
//   "hourglass-empty": "\ue88b",
//   "hourglass-full": "\ue88c",
//   "http": "\ue902",
//   "https": "\ue88d",
//   "image": "\ue3f4",
//   "image-aspect-ratio": "\ue3f5",
//   "import-contacts": "\ue0e0",
//   "import-export": "\ue0c3",
//   "important-devices": "\ue912",
//   "inbox": "\ue156",
//   "indeterminate-check-box": "\ue909",
//   "info": "\ue88e",
//   "info-outline": "\ue88f",
//   "input": "\ue890",
//   "insert-chart": "\ue24b",
//   "insert-comment": "\ue24c",
//   "insert-drive-file": "\ue24d",
//   "insert-emoticon": "\ue24e",
//   "insert-invitation": "\ue24f",
//   "insert-link": "\ue250",
//   "insert-photo": "\ue251",
//   "invert-colors": "\ue891",
//   "invert-colors-off": "\ue0c4",
//   "iso": "\ue3f6",
//   "keyboard": "\ue312",
//   "keyboard-arrow-down": "\ue313",
//   "keyboard-arrow-left": "\ue314",
//   "keyboard-arrow-right": "\ue315",
//   "keyboard-arrow-up": "\ue316",
//   "keyboard-backspace": "\ue317",
//   "keyboard-capslock": "\ue318",
//   "keyboard-hide": "\ue31a",
//   "keyboard-return": "\ue31b",
//   "keyboard-tab": "\ue31c",
//   "keyboard-voice": "\ue31d",
//   "kitchen": "\ueb47",
//   "label": "\ue892",
//   "label-outline": "\ue893",
//   "landscape": "\ue3f7",
//   "language": "\ue894",
//   "laptop": "\ue31e",
//   "laptop-chromebook": "\ue31f",
//   "laptop-mac": "\ue320",
//   "laptop-windows": "\ue321",
//   "last-page": "\ue5dd",
//   "launch": "\ue895",
//   "layers": "\ue53b",
//   "layers-clear": "\ue53c",
//   "leak-add": "\ue3f8",
//   "leak-remove": "\ue3f9",
//   "lens": "\ue3fa",
//   "library-add": "\ue02e",
//   "library-books": "\ue02f",
//   "library-music": "\ue030",
//   "lightbulb-outline": "\ue90f",
//   "line-style": "\ue919",
//   "line-weight": "\ue91a",
//   "linear-scale": "\ue260",
//   "link": "\ue157",
//   "linked-camera": "\ue438",
//   "list": "\ue896",
//   "live-help": "\ue0c6",
//   "live-tv": "\ue639",
//   "local-activity": "\ue53f",
//   "local-airport": "\ue53d",
//   "local-atm": "\ue53e",
//   "local-bar": "\ue540",
//   "local-cafe": "\ue541",
//   "local-car-wash": "\ue542",
//   "local-convenience-store": "\ue543",
//   "local-dining": "\ue556",
//   "local-drink": "\ue544",
//   "local-florist": "\ue545",
//   "local-gas-station": "\ue546",
//   "local-grocery-store": "\ue547",
//   "local-hospital": "\ue548",
//   "local-hotel": "\ue549",
//   "local-laundry-service": "\ue54a",
//   "local-library": "\ue54b",
//   "local-mall": "\ue54c",
//   "local-movies": "\ue54d",
//   "local-offer": "\ue54e",
//   "local-parking": "\ue54f",
//   "local-pharmacy": "\ue550",
//   "local-phone": "\ue551",
//   "local-pizza": "\ue552",
//   "local-play": "\ue553",
//   "local-post-office": "\ue554",
//   "local-printshop": "\ue555",
//   "local-see": "\ue557",
//   "local-shipping": "\ue558",
//   "local-taxi": "\ue559",
//   "location-city": "\ue7f1",
//   "location-disabled": "\ue1b6",
//   "location-off": "\ue0c7",
//   "location-on": "\ue0c8",
//   "location-searching": "\ue1b7",
//   "lock": "\ue897",
//   "lock-open": "\ue898",
//   "lock-outline": "\ue899",
//   "looks": "\ue3fc",
//   "looks-3": "\ue3fb",
//   "looks-4": "\ue3fd",
//   "looks-5": "\ue3fe",
//   "looks-6": "\ue3ff",
//   "looks-one": "\ue400",
//   "looks-two": "\ue401",
//   "loop": "\ue028",
//   "loupe": "\ue402",
//   "low-priority": "\ue16d",
//   "loyalty": "\ue89a",
//   "mail": "\ue158",
//   "mail-outline": "\ue0e1",
//   "map": "\ue55b",
//   "markunread": "\ue159",
//   "markunread-mailbox": "\ue89b",
//   "memory": "\ue322",
//   "menu": "\ue5d2",
//   "merge-type": "\ue252",
//   "message": "\ue0c9",
//   "mic": "\ue029",
//   "mic-none": "\ue02a",
//   "mic-off": "\ue02b",
//   "mms": "\ue618",
//   "mode-comment": "\ue253",
//   "mode-edit": "\ue254",
//   "monetization-on": "\ue263",
//   "money-off": "\ue25c",
//   "monochrome-photos": "\ue403",
//   "mood": "\ue7f2",
//   "mood-bad": "\ue7f3",
//   "more": "\ue619",
//   "more-horiz": "\ue5d3",
//   "more-vert": "\ue5d4",
//   "motorcycle": "\ue91b",
//   "mouse": "\ue323",
//   "move-to-inbox": "\ue168",
//   "movie": "\ue02c",
//   "movie-creation": "\ue404",
//   "movie-filter": "\ue43a",
//   "multiline-chart": "\ue6df",
//   "music-note": "\ue405",
//   "music-video": "\ue063",
//   "my-location": "\ue55c",
//   "nature": "\ue406",
//   "nature-people": "\ue407",
//   "navigate-before": "\ue408",
//   "navigate-next": "\ue409",
//   "navigation": "\ue55d",
//   "near-me": "\ue569",
//   "network-cell": "\ue1b9",
//   "network-check": "\ue640",
//   "network-locked": "\ue61a",
//   "network-wifi": "\ue1ba",
//   "new-releases": "\ue031",
//   "next-week": "\ue16a",
//   "nfc": "\ue1bb",
//   "no-encryption": "\ue641",
//   "no-sim": "\ue0cc",
//   "not-interested": "\ue033",
//   "note": "\ue06f",
//   "note-add": "\ue89c",
//   "notifications": "\ue7f4",
//   "notifications-active": "\ue7f7",
//   "notifications-none": "\ue7f5",
//   "notifications-off": "\ue7f6",
//   "notifications-paused": "\ue7f8",
//   "offline-pin": "\ue90a",
//   "ondemand-video": "\ue63a",
//   "opacity": "\ue91c",
//   "open-in-browser": "\ue89d",
//   "open-in-new": "\ue89e",
//   "open-with": "\ue89f",
//   "pages": "\ue7f9",
//   "pageview": "\ue8a0",
//   "palette": "\ue40a",
//   "pan-tool": "\ue925",
//   "panorama": "\ue40b",
//   "panorama-fish-eye": "\ue40c",
//   "panorama-horizontal": "\ue40d",
//   "panorama-vertical": "\ue40e",
//   "panorama-wide-angle": "\ue40f",
//   "party-mode": "\ue7fa",
//   "pause": "\ue034",
//   "pause-circle-filled": "\ue035",
//   "pause-circle-outline": "\ue036",
//   "payment": "\ue8a1",
//   "people": "\ue7fb",
//   "people-outline": "\ue7fc",
//   "perm-camera-mic": "\ue8a2",
//   "perm-contact-calendar": "\ue8a3",
//   "perm-data-setting": "\ue8a4",
//   "perm-device-information": "\ue8a5",
//   "perm-identity": "\ue8a6",
//   "perm-media": "\ue8a7",
//   "perm-phone-msg": "\ue8a8",
//   "perm-scan-wifi": "\ue8a9",
//   "person": "\ue7fd",
//   "person-add": "\ue7fe",
//   "person-outline": "\ue7ff",
//   "person-pin": "\ue55a",
//   "person-pin-circle": "\ue56a",
//   "personal-video": "\ue63b",
//   "pets": "\ue91d",
//   "phone": "\ue0cd",
//   "phone-android": "\ue324",
//   "phone-bluetooth-speaker": "\ue61b",
//   "phone-forwarded": "\ue61c",
//   "phone-in-talk": "\ue61d",
//   "phone-iphone": "\ue325",
//   "phone-locked": "\ue61e",
//   "phone-missed": "\ue61f",
//   "phone-paused": "\ue620",
//   "phonelink": "\ue326",
//   "phonelink-erase": "\ue0db",
//   "phonelink-lock": "\ue0dc",
//   "phonelink-off": "\ue327",
//   "phonelink-ring": "\ue0dd",
//   "phonelink-setup": "\ue0de",
//   "photo": "\ue410",
//   "photo-album": "\ue411",
//   "photo-camera": "\ue412",
//   "photo-filter": "\ue43b",
//   "photo-library": "\ue413",
//   "photo-size-select-actual": "\ue432",
//   "photo-size-select-large": "\ue433",
//   "photo-size-select-small": "\ue434",
//   "picture-as-pdf": "\ue415",
//   "picture-in-picture": "\ue8aa",
//   "picture-in-picture-alt": "\ue911",
//   "pie-chart": "\ue6c4",
//   "pie-chart-outlined": "\ue6c5",
//   "pin-drop": "\ue55e",
//   "place": "\ue55f",
//   "play-arrow": "\ue037",
//   "play-circle-filled": "\ue038",
//   "play-circle-outline": "\ue039",
//   "play-for-work": "\ue906",
//   "playlist-add": "\ue03b",
//   "playlist-add-check": "\ue065",
//   "playlist-play": "\ue05f",
//   "plus-one": "\ue800",
//   "poll": "\ue801",
//   "polymer": "\ue8ab",
//   "pool": "\ueb48",
//   "portable-wifi-off": "\ue0ce",
//   "portrait": "\ue416",
//   "power": "\ue63c",
//   "power-input": "\ue336",
//   "power-settings-new": "\ue8ac",
//   "pregnant-woman": "\ue91e",
//   "present-to-all": "\ue0df",
//   "print": "\ue8ad",
//   "priority-high": "\ue645",
//   "public": "\ue80b",
//   "publish": "\ue255",
//   "query-builder": "\ue8ae",
//   "question-answer": "\ue8af",
//   "queue": "\ue03c",
//   "queue-music": "\ue03d",
//   "queue-play-next": "\ue066",
//   "radio": "\ue03e",
//   "radio-button-checked": "\ue837",
//   "radio-button-unchecked": "\ue836",
//   "rate-review": "\ue560",
//   "receipt": "\ue8b0",
//   "recent-actors": "\ue03f",
//   "record-voice-over": "\ue91f",
//   "redeem": "\ue8b1",
//   "redo": "\ue15a",
//   "refresh": "\ue5d5",
//   "remove": "\ue15b",
//   "remove-circle": "\ue15c",
//   "remove-circle-outline": "\ue15d",
//   "remove-from-queue": "\ue067",
//   "remove-red-eye": "\ue417",
//   "remove-shopping-cart": "\ue928",
//   "reorder": "\ue8fe",
//   "repeat": "\ue040",
//   "repeat-one": "\ue041",
//   "replay": "\ue042",
//   "replay-10": "\ue059",
//   "replay-30": "\ue05a",
//   "replay-5": "\ue05b",
//   "reply": "\ue15e",
//   "reply-all": "\ue15f",
//   "report": "\ue160",
//   "report-problem": "\ue8b2",
//   "restaurant": "\ue56c",
//   "restaurant-menu": "\ue561",
//   "restore": "\ue8b3",
//   "restore-page": "\ue929",
//   "ring-volume": "\ue0d1",
//   "room": "\ue8b4",
//   "room-service": "\ueb49",
//   "rotate-90-degrees-ccw": "\ue418",
//   "rotate-left": "\ue419",
//   "rotate-right": "\ue41a",
//   "rounded-corner": "\ue920",
//   "router": "\ue328",
//   "rowing": "\ue921",
//   "rss-feed": "\ue0e5",
//   "rv-hookup": "\ue642",
//   "satellite": "\ue562",
//   "save": "\ue161",
//   "scanner": "\ue329",
//   "schedule": "\ue8b5",
//   "school": "\ue80c",
//   "screen-lock-landscape": "\ue1be",
//   "screen-lock-portrait": "\ue1bf",
//   "screen-lock-rotation": "\ue1c0",
//   "screen-rotation": "\ue1c1",
//   "screen-share": "\ue0e2",
//   "sd-card": "\ue623",
//   "sd-storage": "\ue1c2",
//   "search": "\ue8b6",
//   "security": "\ue32a",
//   "select-all": "\ue162",
//   "send": "\ue163",
//   "sentiment-dissatisfied": "\ue811",
//   "sentiment-neutral": "\ue812",
//   "sentiment-satisfied": "\ue813",
//   "sentiment-very-dissatisfied": "\ue814",
//   "sentiment-very-satisfied": "\ue815",
//   "settings": "\ue8b8",
//   "settings-applications": "\ue8b9",
//   "settings-backup-restore": "\ue8ba",
//   "settings-bluetooth": "\ue8bb",
//   "settings-brightness": "\ue8bd",
//   "settings-cell": "\ue8bc",
//   "settings-ethernet": "\ue8be",
//   "settings-input-antenna": "\ue8bf",
//   "settings-input-component": "\ue8c0",
//   "settings-input-composite": "\ue8c1",
//   "settings-input-hdmi": "\ue8c2",
//   "settings-input-svideo": "\ue8c3",
//   "settings-overscan": "\ue8c4",
//   "settings-phone": "\ue8c5",
//   "settings-power": "\ue8c6",
//   "settings-remote": "\ue8c7",
//   "settings-system-daydream": "\ue1c3",
//   "settings-voice": "\ue8c8",
//   "share": "\ue80d",
//   "shop": "\ue8c9",
//   "shop-two": "\ue8ca",
//   "shopping-basket": "\ue8cb",
//   "shopping-cart": "\ue8cc",
//   "short-text": "\ue261",
//   "show-chart": "\ue6e1",
//   "shuffle": "\ue043",
//   "signal-cellular-4-bar": "\ue1c8",
//   "signal-cellular-connected-no-internet-4-bar": "\ue1cd",
//   "signal-cellular-no-sim": "\ue1ce",
//   "signal-cellular-null": "\ue1cf",
//   "signal-cellular-off": "\ue1d0",
//   "signal-wifi-4-bar": "\ue1d8",
//   "signal-wifi-4-bar-lock": "\ue1d9",
//   "signal-wifi-off": "\ue1da",
//   "sim-card": "\ue32b",
//   "sim-card-alert": "\ue624",
//   "skip-next": "\ue044",
//   "skip-previous": "\ue045",
//   "slideshow": "\ue41b",
//   "slow-motion-video": "\ue068",
//   "smartphone": "\ue32c",
//   "smoke-free": "\ueb4a",
//   "smoking-rooms": "\ueb4b",
//   "sms": "\ue625",
//   "sms-failed": "\ue626",
//   "snooze": "\ue046",
//   "sort": "\ue164",
//   "sort-by-alpha": "\ue053",
//   "spa": "\ueb4c",
//   "space-bar": "\ue256",
//   "speaker": "\ue32d",
//   "speaker-group": "\ue32e",
//   "speaker-notes": "\ue8cd",
//   "speaker-notes-off": "\ue92a",
//   "speaker-phone": "\ue0d2",
//   "spellcheck": "\ue8ce",
//   "star": "\ue838",
//   "star-border": "\ue83a",
//   "star-half": "\ue839",
//   "stars": "\ue8d0",
//   "stay-current-landscape": "\ue0d3",
//   "stay-current-portrait": "\ue0d4",
//   "stay-primary-landscape": "\ue0d5",
//   "stay-primary-portrait": "\ue0d6",
//   "stop": "\ue047",
//   "stop-screen-share": "\ue0e3",
//   "storage": "\ue1db",
//   "store": "\ue8d1",
//   "store-mall-directory": "\ue563",
//   "straighten": "\ue41c",
//   "streetview": "\ue56e",
//   "strikethrough-s": "\ue257",
//   "style": "\ue41d",
//   "subdirectory-arrow-left": "\ue5d9",
//   "subdirectory-arrow-right": "\ue5da",
//   "subject": "\ue8d2",
//   "subscriptions": "\ue064",
//   "subtitles": "\ue048",
//   "subway": "\ue56f",
//   "supervisor-account": "\ue8d3",
//   "surround-sound": "\ue049",
//   "swap-calls": "\ue0d7",
//   "swap-horiz": "\ue8d4",
//   "swap-vert": "\ue8d5",
//   "swap-vertical-circle": "\ue8d6",
//   "switch-camera": "\ue41e",
//   "switch-video": "\ue41f",
//   "sync": "\ue627",
//   "sync-disabled": "\ue628",
//   "sync-problem": "\ue629",
//   "system-update": "\ue62a",
//   "system-update-alt": "\ue8d7",
//   "tab": "\ue8d8",
//   "tab-unselected": "\ue8d9",
//   "table-chart": "\ue265",
//   "tablet": "\ue32f",
//   "tablet-android": "\ue330",
//   "tablet-mac": "\ue331",
//   "tag-faces": "\ue420",
//   "tap-and-play": "\ue62b",
//   "terrain": "\ue564",
//   "text-fields": "\ue262",
//   "text-format": "\ue165",
//   "textsms": "\ue0d8",
//   "texture": "\ue421",
//   "theaters": "\ue8da",
//   "thumb-down": "\ue8db",
//   "thumb-up": "\ue8dc",
//   "thumbs-up-down": "\ue8dd",
//   "time-to-leave": "\ue62c",
//   "timelapse": "\ue422",
//   "timeline": "\ue922",
//   "timer": "\ue425",
//   "timer-10": "\ue423",
//   "timer-3": "\ue424",
//   "timer-off": "\ue426",
//   "title": "\ue264",
//   "toc": "\ue8de",
//   "today": "\ue8df",
//   "toll": "\ue8e0",
//   "tonality": "\ue427",
//   "touch-app": "\ue913",
//   "toys": "\ue332",
//   "track-changes": "\ue8e1",
//   "traffic": "\ue565",
//   "train": "\ue570",
//   "tram": "\ue571",
//   "transfer-within-a-station": "\ue572",
//   "transform": "\ue428",
//   "translate": "\ue8e2",
//   "trending-down": "\ue8e3",
//   "trending-flat": "\ue8e4",
//   "trending-up": "\ue8e5",
//   "tune": "\ue429",
//   "turned-in": "\ue8e6",
//   "turned-in-not": "\ue8e7",
//   "tv": "\ue333",
//   "unarchive": "\ue169",
//   "undo": "\ue166",
//   "unfold-less": "\ue5d6",
//   "unfold-more": "\ue5d7",
//   "update": "\ue923",
//   "usb": "\ue1e0",
//   "verified-user": "\ue8e8",
//   "vertical-align-bottom": "\ue258",
//   "vertical-align-center": "\ue259",
//   "vertical-align-top": "\ue25a",
//   "vibration": "\ue62d",
//   "video-call": "\ue070",
//   "video-label": "\ue071",
//   "video-library": "\ue04a",
//   "videocam": "\ue04b",
//   "videocam-off": "\ue04c",
//   "videogame-asset": "\ue338",
//   "view-agenda": "\ue8e9",
//   "view-array": "\ue8ea",
//   "view-carousel": "\ue8eb",
//   "view-column": "\ue8ec",
//   "view-comfy": "\ue42a",
//   "view-compact": "\ue42b",
//   "view-day": "\ue8ed",
//   "view-headline": "\ue8ee",
//   "view-list": "\ue8ef",
//   "view-module": "\ue8f0",
//   "view-quilt": "\ue8f1",
//   "view-stream": "\ue8f2",
//   "view-week": "\ue8f3",
//   "vignette": "\ue435",
//   "visibility": "\ue8f4",
//   "visibility-off": "\ue8f5",
//   "voice-chat": "\ue62e",
//   "voicemail": "\ue0d9",
//   "volume-down": "\ue04d",
//   "volume-mute": "\ue04e",
//   "volume-off": "\ue04f",
//   "volume-up": "\ue050",
//   "vpn-key": "\ue0da",
//   "vpn-lock": "\ue62f",
//   "wallpaper": "\ue1bc",
//   "warning": "\ue002",
//   "watch": "\ue334",
//   "watch-later": "\ue924",
//   "wb-auto": "\ue42c",
//   "wb-cloudy": "\ue42d",
//   "wb-incandescent": "\ue42e",
//   "wb-iridescent": "\ue436",
//   "wb-sunny": "\ue430",
//   "wc": "\ue63d",
//   "web": "\ue051",
//   "web-asset": "\ue069",
//   "weekend": "\ue16b",
//   "whatshot": "\ue80e",
//   "widgets": "\ue1bd",
//   "wifi": "\ue63e",
//   "wifi-lock": "\ue1e1",
//   "wifi-tethering": "\ue1e2",
//   "work": "\ue8f9",
//   "wrap-text": "\ue25b",
//   "youtube-searched-for": "\ue8fa",
//   "zoom-in": "\ue8ff",
//   "zoom-out": "\ue900",
//   "zoom-out-map": "\ue56b"
// };

// // Streamline Light glyphMap - Common streamline light icons
// export const streamlineLightGlyphMap: Record<string, string> = {
//   "user": "\ue001",
//   "users": "\ue002",
//   "user-circle": "\ue003",
//   "user-add": "\ue004",
//   "user-remove": "\ue005",
//   "user-check": "\ue006",
//   "user-close": "\ue007",
//   "star": "\ue010",
//   "star-half": "\ue011",
//   "heart": "\ue012",
//   "heart-full": "\ue013",
//   "home": "\ue020",
//   "office": "\ue021",
//   "pencil": "\ue030",
//   "pen": "\ue031",
//   "eraser": "\ue032",
//   "settings": "\ue040",
//   "cog": "\ue041",
//   "gear": "\ue042",
//   "wrench": "\ue043",
//   "hammer": "\ue044",
//   "magic-wand": "\ue045",
//   "search": "\ue050",
//   "zoom-in": "\ue051",
//   "zoom-out": "\ue052",
//   "search-plus": "\ue053",
//   "search-minus": "\ue054",
//   "lock": "\ue060",
//   "unlock": "\ue061",
//   "key": "\ue062",
//   "shield": "\ue063",
//   "shield-check": "\ue064",
//   "bell": "\ue070",
//   "bell-off": "\ue071",
//   "bell-ring": "\ue072",
//   "notification": "\ue073",
//   "mail": "\ue080",
//   "envelope": "\ue081",
//   "envelope-open": "\ue082",
//   "inbox": "\ue083",
//   "outbox": "\ue084",
//   "calendar": "\ue090",
//   "calendar-add": "\ue091",
//   "calendar-remove": "\ue092",
//   "calendar-check": "\ue093",
//   "clock": "\ue094",
//   "time": "\ue095",
//   "alarm": "\ue096",
//   "stopwatch": "\ue097",
//   "hourglass": "\ue098",
//   "camera": "\ue0a0",
//   "camera-off": "\ue0a1",
//   "image": "\ue0a2",
//   "images": "\ue0a3",
//   "picture": "\ue0a4",
//   "folder": "\ue0b0",
//   "folder-open": "\ue0b1",
//   "folder-add": "\ue0b2",
//   "folder-remove": "\ue0b3",
//   "file": "\ue0b4",
//   "file-add": "\ue0b5",
//   "file-remove": "\ue0b6",
//   "file-check": "\ue0b7",
//   "file-text": "\ue0b8",
//   "document": "\ue0b9",
//   "cloud": "\ue0c0",
//   "cloud-upload": "\ue0c1",
//   "cloud-download": "\ue0c2",
//   "cloud-sync": "\ue0c3",
//   "cloud-check": "\ue0c4",
//   "upload": "\ue0c5",
//   "download": "\ue0c6",
//   "share": "\ue0d0",
//   "share-alt": "\ue0d1",
//   "link": "\ue0d2",
//   "unlink": "\ue0d3",
//   "chain": "\ue0d4",
//   "tag": "\ue0e0",
//   "tags": "\ue0e1",
//   "bookmark": "\ue0e2",
//   "bookmark-add": "\ue0e3",
//   "flag": "\ue0e4",
//   "pin": "\ue0e5",
//   "map": "\ue0f0",
//   "map-marker": "\ue0f1",
//   "map-pin": "\ue0f2",
//   "location": "\ue0f3",
//   "navigation": "\ue0f4",
//   "compass": "\ue0f5",
//   "globe": "\ue0f6",
//   "world": "\ue0f7",
//   "phone": "\ue100",
//   "phone-call": "\ue101",
//   "phone-incoming": "\ue102",
//   "phone-outgoing": "\ue103",
//   "phone-missed": "\ue104",
//   "smartphone": "\ue105",
//   "mobile": "\ue106",
//   "tablet": "\ue107",
//   "laptop": "\ue108",
//   "desktop": "\ue109",
//   "monitor": "\ue10a",
//   "tv": "\ue10b",
//   "printer": "\ue10c",
//   "keyboard": "\ue10d",
//   "mouse": "\ue10e",
//   "headphones": "\ue10f",
//   "volume": "\ue110",
//   "volume-high": "\ue111",
//   "volume-low": "\ue112",
//   "volume-mute": "\ue113",
//   "volume-off": "\ue114",
//   "music": "\ue120",
//   "music-note": "\ue121",
//   "play": "\ue122",
//   "pause": "\ue123",
//   "stop": "\ue124",
//   "forward": "\ue125",
//   "backward": "\ue126",
//   "skip-forward": "\ue127",
//   "skip-backward": "\ue128",
//   "repeat": "\ue129",
//   "shuffle": "\ue12a",
//   "video": "\ue130",
//   "video-camera": "\ue131",
//   "film": "\ue132",
//   "movie": "\ue133",
//   "cart": "\ue140",
//   "shopping-cart": "\ue141",
//   "shopping-bag": "\ue142",
//   "basket": "\ue143",
//   "credit-card": "\ue144",
//   "wallet": "\ue145",
//   "money": "\ue146",
//   "dollar": "\ue147",
//   "euro": "\ue148",
//   "pound": "\ue149",
//   "gift": "\ue14a",
//   "box": "\ue14b",
//   "package": "\ue14c",
//   "truck": "\ue14d",
//   "delivery": "\ue14e",
//   "chat": "\ue150",
//   "message": "\ue151",
//   "comment": "\ue152",
//   "comments": "\ue153",
//   "speech-bubble": "\ue154",
//   "thumbs-up": "\ue160",
//   "thumbs-down": "\ue161",
//   "like": "\ue162",
//   "dislike": "\ue163",
//   "plus": "\ue170",
//   "minus": "\ue171",
//   "close": "\ue172",
//   "check": "\ue173",
//   "check-circle": "\ue174",
//   "close-circle": "\ue175",
//   "info": "\ue176",
//   "info-circle": "\ue177",
//   "question": "\ue178",
//   "question-circle": "\ue179",
//   "exclamation": "\ue17a",
//   "exclamation-circle": "\ue17b",
//   "warning": "\ue17c",
//   "warning-triangle": "\ue17d",
//   "alert": "\ue17e",
//   "error": "\ue17f",
//   "arrow-up": "\ue180",
//   "arrow-down": "\ue181",
//   "arrow-left": "\ue182",
//   "arrow-right": "\ue183",
//   "arrow-up-circle": "\ue184",
//   "arrow-down-circle": "\ue185",
//   "arrow-left-circle": "\ue186",
//   "arrow-right-circle": "\ue187",
//   "chevron-up": "\ue188",
//   "chevron-down": "\ue189",
//   "chevron-left": "\ue18a",
//   "chevron-right": "\ue18b",
//   "triangle-up": "\ue18c",
//   "triangle-down": "\ue18d",
//   "triangle-left": "\ue18e",
//   "triangle-right": "\ue18f",
//   "menu": "\ue190",
//   "menu-hamburger": "\ue191",
//   "menu-dots": "\ue192",
//   "more-horizontal": "\ue193",
//   "more-vertical": "\ue194",
//   "grid": "\ue1a0",
//   "grid-large": "\ue1a1",
//   "grid-small": "\ue1a2",
//   "list": "\ue1a3",
//   "layout": "\ue1a4",
//   "columns": "\ue1a5",
//   "rows": "\ue1a6",
//   "sidebar": "\ue1a7",
//   "layers": "\ue1a8",
//   "copy": "\ue1b0",
//   "paste": "\ue1b1",
//   "cut": "\ue1b2",
//   "clipboard": "\ue1b3",
//   "trash": "\ue1b4",
//   "trash-empty": "\ue1b5",
//   "delete": "\ue1b6",
//   "remove": "\ue1b7",
//   "edit": "\ue1b8",
//   "save": "\ue1b9",
//   "filter": "\ue1c0",
//   "filter-off": "\ue1c1",
//   "sort": "\ue1c2",
//   "sort-up": "\ue1c3",
//   "sort-down": "\ue1c4",
//   "refresh": "\ue1d0",
//   "reload": "\ue1d1",
//   "sync": "\ue1d2",
//   "rotate": "\ue1d3",
//   "rotate-left": "\ue1d4",
//   "rotate-right": "\ue1d5",
//   "undo": "\ue1d6",
//   "redo": "\ue1d7",
//   "maximize": "\ue1e0",
//   "minimize": "\ue1e1",
//   "fullscreen": "\ue1e2",
//   "fullscreen-exit": "\ue1e3",
//   "expand": "\ue1e4",
//   "collapse": "\ue1e5",
//   "eye": "\ue1f0",
//   "eye-off": "\ue1f1",
//   "visible": "\ue1f2",
//   "invisible": "\ue1f3",
//   "show": "\ue1f4",
//   "hide": "\ue1f5"
// };

// // Streamline Regular glyphMap - Common streamline regular icons (similar to light but regular weight)
// export const streamlineRegularGlyphMap: Record<string, string> = {
//   ...streamlineLightGlyphMap // For now, using the same mappings with different font-family
// };
